Design/Design/urls.py
from django.contrib import admin
from django.urls import path,include
from blog import views

urlpatterns = [
    path('',views.index,name='index'),
    path('team_intro',views.team_intro,name='team'),
    path('research',views.research,name='research'),
    path('future',views.future,name='future'),
    # path('',views.index1,name='index1'),
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('login/',views.login,name='login'),
    path('logsucess/',views.logsuccess,name='loginsuccess'),
    path('register/',views.register,name='register'),
    path('forget',views.forget_password,name='forget'),
    path('reset',views.reset,name='reset'),
    path('logout',views.log_out,name='logout'),
    path('summernote/', include('django_summernote.urls')),
    
]


Design/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('',views.home,name='home'),
    path('category/<int:id>', views.category, name='category'),
    path('tags/', views.tags, name='tags'),
    path('tags/<int:id>/', views.tag_detail, name='tags_detail'),
    path('articles/<int:id>/', views.detail, name='detail'),
    path('commentpost',views.commentpost,name='commentpost'),
    path('userinfo',views.user_info,name='userinfo'),
    path('info/<comment_id>',views.comment_del,name="comm_del"),
    path('commentdel',views.comment_del,name='comment_del'),
    path('search/',views.search,name='search'),
    path('upload',views.upload,name='upload'),
    path('test',views.test,name='test'),
]

Design/blog/forms.py
from django import forms
from blog.models import ArticleComment


class ArticleCommentForm(forms.Form):
    body = forms.CharField(required=True, label="",
                           error_messages={'required': '...',
                                           'min_length': '再输入点内容吧'},
                           min_length=2, widget=forms.Textarea(attrs={'placeholder': '路过匆匆，何不留下您的看法呢....'}))
    class Meta:
        model = ArticleComment
        fields = ['body,user_name']

    def clean_body(self):
        message = self.cleaned_data['body']
        if "fuck" in message:
            raise forms.ValidationError('请文明用语')
        return message
class historyinfo(forms.Form):
    kmnc=forms.CharField(max_length=20)
    nbc=forms.CharField(max_length=20)
    snac=forms.CharField(max_length=20)
    tknc=forms.CharField(max_length=20)


    def __str__(self):
        return self.name



Design/blog/views.py
from PIL import Image
from django.contrib.auth.hashers import check_password
import collections
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
import json
from django.http import Http404, HttpResponse
from django.shortcuts import render
from blog.forms import ArticleCommentForm
from Design import settings
from blog.models import User, Article, Tag, ArticleComment, Category,uploadmnist,uploadmodel,presentation,mnist2,model2
from deepgauge.deepgauge_metrics import kmnc,nbc,tknc
from deepgauge.load_data import gen_data,load_mnist_data,screen_data,divide_mnist_data
from deepgauge.mnist_pic_transform_npy import get_mnist_test_npy
import numpy as np
from blog.forms import historyinfo


def index(request):
    return render(request,'blog/newindex.html')
def team_intro(request):
    return render(request,'blog/team_intr.html')
def research(request):
    return render(request,'blog/research.html')
def future(request):
    return render(request,'blog/future.html')

def index1(request):
    return render(request,'blog/index1.html')

def login(request):
    if request.method == 'POST':
        user_name = request.POST.get('username','')
        pass_word = request.POST.get('password','')
        user = User.objects.filter(username=user_name)  #查看数据库里是否有该用户名
        if user:#如果存在
            user = User.objects.get(username = user_name)#读取该用户信息
            if pass_word==user.password:#检查密码是否匹配
                request.session['IS_LOGIN'] = True
                request.session['nickname'] = user.nickname
                request.session['username'] = user_name
                avatar = 'media/' + user_name + '.png'
                request.session['avatar'] = avatar
                return render(request,'blog/success.html',{'user':user})
            else:
                return render(request,'blog/login.html',{'error': '密码错误!'})
        else:
            return render(request, 'blog/login.html', {'error': '用户名不存在!'})
    else:
        return render(request,'blog/login.html')

def logsuccess(request):
    return render(request,'blog/success.html')

def register(request):
    if request.method =='POST':
        user_name = request.POST.get('username','')
        pass_word_1 = request.POST.get('password_1','')
        pass_word_2 = request.POST.get('password_2','')
        nick_name = request.POST.get('nickname','')
        email = request.POST.get('email','')
        avatar = request.FILES.get('avatar')
        if User.objects.filter(username = user_name):
            return render(request,'blog/register.html',{'error':'用户已存在'})
            #将表单写入数据库
        if(pass_word_1 != pass_word_2):
            return render(request, 'blog/register.html', {'error': '两次密码请输入一致'})
        user = User()
        if avatar:
            user.avatar = 'media/' + user_name + '.png'
            img = Image.open(avatar)
            size = img.size
            print(size)
            # 因为是要圆形，所以需要正方形的图片
            r2 = min(size[0], size[1])
            if size[0] != size[1]:
                img = img.resize((r2, r2), Image.ANTIALIAS)

                # 最后生成圆的半径
            r3 = int(r2/2)
            img_circle = Image.new('RGBA', (r3 * 2, r3 * 2), (255, 255, 255, 0))
            pima = img.load()  # 像素的访问对象
            pimb = img_circle.load()
            r = float(r2 / 2)  # 圆心横坐标

            for i in range(r2):
                for j in range(r2):
                    lx = abs(i - r)  # 到圆心距离的横坐标
                    ly = abs(j - r)  # 到圆心距离的纵坐标
                    l = (pow(lx, 2) + pow(ly, 2)) ** 0.5  # 三角函数 半径

                    if l < r3:
                        pimb[i - (r - r3), j - (r - r3)] = pima[i, j]
            img_circle.save('blog/static/media/'+user_name+'.png')
        user.username = user_name
        user.password = pass_word_1
        user.email = email
        user.nickname = nick_name
        user.save()
            #返回注册成功页面
        return render(request,'blog/index.html')
    else:
        return render(request,'blog/register.html')

def forget_password(request):
    if request.method == 'POST':
        user_name = request.POST.get('username','')
        email = request.POST.get('email','')
        user = User.objects.filter(username = user_name)
        if user:
            user = User.objects.get(username = user_name)
            if(user.email == email):
                request.session['user_name'] = user_name
                return render(request,'blog/reset.html')
            else:
                return render(request,'blog/forget.html',{'error':'您的用户名和邮箱不匹配！'})
        else:
            return render(request,'blog/forget.html',{'error':'请输入正确的用户名'})
    else:
        return  render(request,'blog/forget.html')

def reset(request):
    if request.method == 'POST':
        pass_word1 = request.POST.get('password1','')
        pass_word2 = request.POST.get('password2','')
        user_name = request.session['user_name']
        user = User.objects.get(username = user_name)
        if pass_word1 == pass_word2:
            user.password = pass_word1
            user.save()
            return render(request,'blog/login.html')
        else:
            return render(request,'blog/reset.html', {'error': '两次密码输入不一致！'})
    else:
        return render(request,'blog/reset.html')

def log_out(request):
    del request.session['IS_LOGIN']
    del request.session['username']
    del request.session['nickname']
    return render(request,'blog/index.html')

def home(request):  # 主页
    is_login = request.session.get('IS_LOGIN',False)
    if is_login:
        posts = Article.objects.all()  # 获取全部的Article对象
        paginator = Paginator(posts, settings.PAGE_NUM)  # 每页显示数量，对应settings.py中的PAGE_NUM
        page = request.GET.get('page')  # 获取URL中page参数的值
        try:
            post_list = paginator.page(page)
        except PageNotAnInteger:
            post_list = paginator.page(1)
        except EmptyPage:
            post_list = paginator.page(paginator.num_pages)
        nickname = request.session['nickname']
        username = request.session['username']
        avatar = request.session['avatar']

        return render(request, 'blog/home.html', {'post_list': post_list, 'nickname': nickname,'avatar':avatar})
    # if request.method=='POST':
    #     presentations = presentation.objects.all()
    #     return render(request,'blog/home.html',locals())
    # return render(request,'blog/home.html')

def detail(request, id):  # 查看文章详情
    try:
        post = Article.objects.get(article_id=str(id))
        post.viewed()   # 更新浏览次数
        tags = post.tags.all()  # 获取文章对应所有标签
    except Article.DoesNotExist:
        raise Http404
    comments = ArticleComment.objects.filter(article = str(id))
    paginator = Paginator(comments, 3)  # 每页显示3条评论
    page = request.GET.get('page')  # 获取URL中page参数的值
    try:
        comment_list = paginator.page(page)
    except PageNotAnInteger:
        comment_list = paginator.page(1)
    except EmptyPage:
        comment_list = paginator.page(paginator.num_pages)
    previous_post = Article.objects.filter(article_id=str(id-1))
    if previous_post and id!=0:
        previous_post = Article.objects.get(article_id=str(id-1))
    next_post = Article.objects.filter(article_id=str(id+1))
    if next_post:
        next_post = Article.objects.get(article_id=str(id+1))
    return render(request, 'blog/post.html', {'post': post, 'nickname':request.session['nickname'],'tags': tags,'comment_list':comment_list,'previouspost':previous_post,'nextpost':next_post,'avatar':request.session['avatar']})

def commentpost(request):
    if request.method == 'POST':
        comment = request.POST.get('comment','')
        id = request.POST.get('id')
        print("ok")
        if comment!='':
            message = comment
            user_img = 'media/'+request.session['username']+'.png'
            nick_name = request.session['nickname']
            user_name = request.session['username']
            article = Article.objects.get(article_id = str(id))
            newrecord = ArticleComment()
            #newrecord.username = user_name
            newrecord.body = message
            newrecord.article = id
            newrecord.userimg = user_img
            newrecord.username = user_name
            newrecord.nickname = nick_name
            newrecord.title = article.title
            newrecord.save()
            user = User.objects.get(username = user_name)
            user.comment()
            return HttpResponse()

def tags(request):
    nickname = request.session['nickname']
    tags = Tag.objects.all()
    paginator = Paginator(tags, settings.TAG_NUM)  # 每页显示数量，对应settings.py中的PAGE_NUM
    page = request.GET.get('page')  # 获取URL中page参数的值
    try:
        tags = paginator.page(page)
    except PageNotAnInteger:
        tags = paginator.page(1)
    except EmptyPage:
        tags = paginator.page(paginator.num_pages)
    return render(request,'blog/tags.html', {'tag_list': tags,'nickname':nickname,'avatar':request.session['avatar']})

def tag_detail(request,id):
    posts =Article.objects.filter(tags = id)
    tag = Tag.objects.get(id = id)
    paginator = Paginator(posts, settings.PAGE_NUM)  # 每页显示数量，对应settings.py中的PAGE_NUM
    page = request.GET.get('page')  # 获取URL中page参数的值
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except EmptyPage:
        post_list = paginator.page(paginator.num_pages)
    return render(request, 'blog/tags_detail.html', {'post_list': post_list,'tag':tag,'nickname': request.session['nickname'],'avatar':request.session['avatar']})

def category(request,id):
    nickname = request.session['nickname']
    posts =Article.objects.filter(category_id = str(id))

Design/blog/templates/blog/Untitled-1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
       
       
       var a=['lb','df','bjy','xr']; 
       
       for(i in a)
       {function button_onclick()
       {   var c=i;
           alert("你要购买"+a[c]);
           
       } 
        document.write("<li>"+a[i] );
        document.write("<input type=\"button\" value=\"购买\"  onclick=\"return button_onclick()\"");
        } 
  
  
       

      
      
        
    </script>
    
</body>
</html>

Design/blog/templates/blog/post.html
{% load static %}
<html lang="zh">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="newboy-blog">

    <!-- CSS -->
    <title>{{post.title}}</title>
    <link href="{%static 'css/font-awesome.min.css'%}" rel="stylesheet"/>
    <link rel="shortcut icon" href="{% static 'css/images/南京工业大学小图标.png' %}">
    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <!-- Custom styles for our template -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css'%}" media="screen" >
    <link rel="stylesheet" href="{% static 'css/blog_detail.css' %}">
    <script src="{%static 'js/jquery.min.js'%}"></script>
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
</head>

<body>
  <!--导航栏-->
    <div class="navbar navbar-inverse navbar-fixed-top headroom" >
        <div class="container">
            <div class="navbar-header">
                <!-- Button for smallest screens -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                <a class="navbar-brand"><img src="{%static 'css/images/lo.png'%}" alt="Progressus HTML5 template"></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{%url 'blog:home'%}">首页</a></li>
                    <li><a href="{%url 'blog:tags'%}">标签</a></li>
                    <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
                    <li><img src="{%static avatar%}" width="60" ></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{nickname}}<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{%url 'blog:userinfo'%}">个人中心</a></li>
                            <li class="divider"></li>
                            <li><a href="{%url 'logout'%}">注销</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div>
           <section class="blog">
            <header>
                <h2 class="text-center"><font size=50px>{{ post.title }}</font></h2>

                    <p class="text-center blog-time">
                        <i class="fa fa-columns"></i> 发布时间: {{ post.created_time|date:'Y/m/d H:m:s'}}&nbsp&nbsp
                        | <i class="fa fa-folder"></i> 分类于 <a href="{%url 'blog:category' id=post.category_id%}">{{ post.category }}</a>&nbsp&nbsp
                        | <i class="fa fa-tags"></i> 标签:
                          {% for tag in tags %}
                            <a href="{%url 'blog:tags_detail' id=tag.id%}">{{ tag }}</a>
                          {% endfor %}&nbsp;&nbsp;
                        | <i class="fa fa-edit"></i>热度：{{ post.views }}
                    </p>
            </header>

                <div class="post-description" style="padding: 20px 350px 20px 350px;font-size: 20px;" >
                    <p>
                        {{ post.content|safe}}<!--safe标签展现给用户实际内容-->
                    </p>
                </div>
        </section>

    <!-- 上下篇文章切换 开始-->
    <div class="jumbotron" style="min-height: 100px">
        {% if previouspost %}
            <a class="btn" href="{% url 'blog:detail' id=previouspost.article_id %}" style="text-decoration: none; float: left;font-size: 20px;">
                <i class="fa fa-angle-left"></i>&nbsp;&nbsp;上一篇：{{ previouspost.title }}
            </a>
        {% endif %}
        {% if nextpost %}
            <a class="btn" href="{% url 'blog:detail' id=nextpost.article_id %}" style="text-decoration: none; float: right;font-size: 20px;">
                下一篇：{{ nextpost.title }}&nbsp;&nbsp;
                <i class="fa fa-angle-right"></i>
            </a>
        {% endif %}

    <!-- 上下篇文章切换 结束-->
            <article style="padding:100px 100px 100px 50px">
                <h2 style="font-family: KaiTi;">评论列表</h2>
        {% for comm in comment_list %}
                <p style="width: 1000px;font-size: 20px">{{comm.body}}</p>
                <p class="text-right" style="width: 1050px"><img src="{%static comm.userimg%}" width="100">&nbsp;&nbsp;&nbsp;&nbsp;<font color="grey" size="4px">{{comm.nickname}}</font>  <font color="#6C6C6C" size="4px">&nbsp;&nbsp;&nbsp;&nbsp;{{comm.createtime}}</font></p>
                <hr>
        {% endfor %}
        {% if comment_list.object_list and comment_list.paginator.num_pages > 1 %}
                    <div>
            {% if comment_list.has_previous %}
              <ul class="pager">
                <li class="previous"><a href="?page={{ comment_list.previous_page_number }}"><span aria-hidden="true">&larr;</span> Older</a></li>
            </ul>
            {% endif %}
            {% if comment_list.has_next %}
              <ul class="pager">
                <li class="next"><a  href="?page={{ comment_list.next_page_number }}">Newer <span aria-hidden="true">&rarr;</span></a></li>
              </ul>
            {% endif %}
                    </div>
                </article>
    {% endif %}
    <div class="row">
        <div class="col-sm-6">
            <div style="padding-top: 100px">
                <h2 style="font-family: KaiTi;">新的评论</h2>
                <form id="" method="post" enctype="multipart/form-data">
                    <textarea  id='comment'  style="width: 100%;height: 20%;"></textarea>
                    <input type="text" id="articleid" value="{{post.article_id}}" style="display:none">
                    <a type="text" id="postaddress" href="{%url 'blog:commentpost'%}" style="display: none"></a>
               <a class="btn btn-default" style="width: 100%;"  onclick="commentpost()">提交</a>
                </form>
            </div>
        </div>
        <div class="col-sm-6">
            <img src="{%static 'css/images/peiqi.png'%}" width="50%">
        </div>
      </div>
     </div>
    </div>
   <footer class="top-space" style="background: #191919; padding: 15px 0; color: #777; font-size: 12px;">
            <div class="container">
                <p class="text-center">Copyright &copy; 2020,Ericam blog </p>
            </div>
  </footer>
</body>
</html>
<script>
function commentpost(){
        var comment = document.getElementById("comment").value;
        var id = document.getElementById("articleid").value;
        var postaddress = $("#postaddress").attr('href');
         $.ajax({   
                 url: postaddress,     //请求url地址
                 type: "POST",
                 data: {"id":id,"comment":comment},       //发送post请求携带的数据信息
                //dataType: "json",     //期望返回的数据格式，也可以不设置
                success: function (data) 
                {
                	alert("评论成功");
                    document.getElementById("comment").value="";
                    history.go(0);
                },
                error:function () {
                    alert("服务器错误，评论错误");
                }
            })
    }
</script>

Design/blog/templates/blog/success.html
{% load static %}
<html lang="zh">
  <head>
    <meta charset="utf-8">
    <title>首页-newboy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="new boy">

    <!-- CSS -->
	<link rel="shortcut icon" href="{% static 'images/南京工业大学小图标.png' %}">
	<link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<!-- Custom styles for our template -->
	<link rel="stylesheet" href="{% static 'css/bootstrap-theme.css'%}" media="screen" >
	<link rel="stylesheet" href="{% static 'css/blog.css' %}">
	<link rel="stylesheet" href="{% static 'css/log.css' %}">
</head>

<body class="back">
  <script src = "E:/bootstrap/bootstrap-3.3.7-dist/bootstrap-3.3.7-dist/js/jquery.min.js"></script>
  <!--导航栏-->
	<div class="navbar navbar-inverse navbar-fixed-top headroom" >
		<div class="container">
			<div class="container-fluid">
			  <div class="navbar-header">
				<!-- Button for smallest screens -->
				  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
				  <a class="navbar-brand"><img src="{%static 'css/images/lo.png'%}" alt="Progressus HTML5 template"></a>
			  </div>

        <ul class="nav navbar-nav navbar-right">
            <li><a><font size="4" color="white">{{user.nickname}}</font></a></li>
            <li><a href="{%url 'index'%}"><i class="fa fa-sighout"></i><font size="4">注销</font></a></li>
        </ul>
    </div>
	</div>
</div>

	  <center>
    <div class="container" style="padding-top:300px;min-height:800px">
      <div class="row">,.
        <p class="lead"><font color="white"">这里有好多好多资源喔，尽情的享用吧(〃'▽'〃)</font></p>
        <p class="tagline"><font color="white">如果您有优秀的资源，欢迎投递哦</font></p>
        <p><a class="btn btn-action btn-lg" role="button" href="{%url 'blog:home'%}">START NOW</a></p>
      </div>
    </div>
	</center>

   
</body>
</html>

Design/blog/templates/blog/tags_detail.html
{% block content %}
{% load static %}
<html lang="zh">
  <head>
    <meta charset="utf-8">
    <title>标签-NEWBOY</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="南农信息资源共享系统，NJAU">
    <meta name="author" content="Ericam_">

    <!-- CSS -->
    <title>newboy-个人博客</title>
    <link href="{%static 'css/font-awesome.min.css'%}" rel="stylesheet"/>
    <link rel="shortcut icon" href="{% static 'css/images/南京工业大学小图标.png' %}">
    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <!-- Custom styles for our template -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css'%}" media="screen" >
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <!--<script src="http://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
    <script src="{%static 'js/jquery.min.js'%}"></script>
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
</head>

<body style="background-color: #F0F0F0">
  <!--导航栏-->
    <div class="navbar navbar-inverse navbar-fixed-top headroom" >
        <div class="container">
            <div class="navbar-header">
                <!-- Button for smallest screens -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{%url 'blog:home'%}">首页</a></li>
                    <li class="active"><a href="{%url 'blog:tags'%}">标签</a></li>
                    <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
                    <li><img src="{%static avatar%}" width="60" ></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{nickname}}<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{%url 'blog:userinfo'%}">个人中心</a></li>
                            <li class="divider"></li>
                            <li><a href="{%url 'logout'%}">注销</a></li>
                        </ul>
                    </li>
                </ul>

                <!--搜索栏-->
                <form class="navbar-form navbar-right" method="POST" action="{%url 'blog:search'%}"> <!--navbar-form:控制搜索表单与其他元素水平-->
                    <div class="form-group">
                        <input type="text" name="info" class="form-control" placeholder="关键字">
                    </div>
                    <button type="submit" class="btn btn-success">Search</button>
                </form>
            </div><!--/.nav-collapse -->
        </div>
    </div>

    <div  style="padding:50px 0px 0px 200px;background-color: #00CACA;margin: 40px;" >
        <div>
            <div class="clr"></div>
            <div><h1><a><img src="{%static 'css/images/ED.png'%}"></a></h1></div>
            <div class="clr"></div>
        </div>
    </div>
    <!-- container -->
    <div class="container" style="background-color:#FCFCFC;padding-bottom: 50px;min-height: 800px" >
        <div class="row">
            <!-- Article main content -->
            <article class="col-sm-8 maincontent">
                <div>
        {% for post in post_list %}
                <article>
                    <h3><a href="{%url 'blog:detail' id=post.article_id%}">{{ post.title }}</a></h3>
                    <p class="blog-time"><font color="#ADADAD">
                        <i class="fa fa-columns"></i> 发表于{{ post.created_time |date:'Y/m/d'}}&nbsp;&nbsp;
                        | <i class="fa fa-folder"></i> 分类于 <a class="post-category post-category-pure" href="{%url 'blog:category' id=post.category_id%}">{{ post.category }}</a>&nbsp;&nbsp;
                        | 热度：{{ post.views }}</font>
                    </p>
        {% endfor %}
        {% if post_list.object_list and post_list.paginator.num_pages > 1 %}
                    <div>
            {% if post_list.has_previous %}
              <ul class="pager">
                <li class="previous"><a href="?page={{ post_list.previous_page_number }}"><span aria-hidden="true">&larr;</span> Older</a></li>
            </ul>
            {% endif %}
            {% if post_list.has_next %}
              <ul class="pager">
                <li class="next"><a  href="?page={{ post_list.next_page_number }}">Newer <span aria-hidden="true">&rarr;</span></a></li>
              </ul>
            {% endif %}
                    </div>
                </article>
    {% endif %}
    </div><!-- /.blog-post -->

            </article>
            <!-- /Article -->

            <!-- Sidebar -->
            <aside class="col-sm-4 sidebar sidebar-right">

                <div class="widget" style="padding-top: 100px">
                    <h4>食用须知</h4>
                    <ul class="list-unstyled list-spaces">
                        <li>课程信息资料主要来源于群组，感谢大家的无私贡献</li>
                        <li>软件破解版仅用于帮助大家学习</li>
                        <li>优秀资源与资料请用留言板告知，感谢您的帮助</li>
                        <li>希望大家多多宣传本站~</li>
                        <li>合作请戳-->私信<a href="https://www.zhihu.com/people/qing-ru-han/activities">知乎</a></li>
                    </ul>
                </div>
            </aside>
            <!-- /Sidebar -->

        </div>
    </div>  <!-- /container -->


   <footer>
        <div class="footer2">
            <div class="container">
                <p class="text-center">Copyright &copy; 2018</p>
            </div>
        </div>
  </footer>
</body>
</html>
{% endblock %}